// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmh8Zp3I2hKBIArpq1dbQEn1M8lKUBnVY',
    appId: '1:447251651704:web:fb4e8cd36cbbf39648218d',
    messagingSenderId: '447251651704',
    projectId: 'agromotion-8a7f8',
    authDomain: 'agromotion-8a7f8.firebaseapp.com',
    databaseURL: 'https://agromotion-8a7f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'agromotion-8a7f8.firebasestorage.app',
    measurementId: 'G-ZZEW4M1P0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1TjVU-IELdqjpr3sd-bR4aTBj5UARAyg',
    appId: '1:447251651704:android:9d5ade755ab6852748218d',
    messagingSenderId: '447251651704',
    projectId: 'agromotion-8a7f8',
    databaseURL: 'https://agromotion-8a7f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'agromotion-8a7f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDExITNqka0N66W4vXA-NJkNkHS7x5bo0c',
    appId: '1:447251651704:ios:068151d83bdcf8ca48218d',
    messagingSenderId: '447251651704',
    projectId: 'agromotion-8a7f8',
    databaseURL: 'https://agromotion-8a7f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'agromotion-8a7f8.firebasestorage.app',
    androidClientId: '447251651704-rjgfglfhh0112h6lmj8btpo3enljjk9i.apps.googleusercontent.com',
    iosClientId: '447251651704-ng3k3cdie1b752285pckssisdtnkhgoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.feedBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDExITNqka0N66W4vXA-NJkNkHS7x5bo0c',
    appId: '1:447251651704:ios:068151d83bdcf8ca48218d',
    messagingSenderId: '447251651704',
    projectId: 'agromotion-8a7f8',
    databaseURL: 'https://agromotion-8a7f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'agromotion-8a7f8.firebasestorage.app',
    androidClientId: '447251651704-rjgfglfhh0112h6lmj8btpo3enljjk9i.apps.googleusercontent.com',
    iosClientId: '447251651704-ng3k3cdie1b752285pckssisdtnkhgoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.feedBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmh8Zp3I2hKBIArpq1dbQEn1M8lKUBnVY',
    appId: '1:447251651704:web:c61cdeac00aaaa5c48218d',
    messagingSenderId: '447251651704',
    projectId: 'agromotion-8a7f8',
    authDomain: 'agromotion-8a7f8.firebaseapp.com',
    databaseURL: 'https://agromotion-8a7f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'agromotion-8a7f8.firebasestorage.app',
    measurementId: 'G-6KKGDR0851',
  );

}